# Working with a CSV

# 1.importing pandas

In [2]:
import pandas as pd

# 2.Reading a CSV

In [3]:
df = pd.read_csv('Mall_Customers.csv')

In [4]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

# 3.Opening a CSV file from a URL

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# 4.Index_col parameter

In [6]:
df = pd.read_csv('Mall_Customers.csv')

In [7]:
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

here, the default index and the customerID are both doing the same job as index, so we can remove one of the indexes using the index_col parameter

In [8]:
df = pd.read_csv('Mall_Customers.csv', index_col  = 'CustomerID')

In [9]:
df

            Gender  Age  Annual Income (k$)  Spending Score (1-100)
CustomerID
1             Male   19                  15                      39
2             Male   21                  15                      81
3           Female   20                  16                       6
4           Female   23                  16                      77
5           Female   31                  17                      40
...            ...  ...                 ...                     ...
196         Female   35                 120                      79
197         Female   45                 126                      28
198           Male   32                 126                      74
199           Male   32                 137                      18
200           Male   30                 137                      83

[200 rows x 4 columns]

now, we only have one index instead of two.

# 5. usecols parameter

suppose, we only want to use the columns age, customerId and spending score column instead of all the columns in the data, so we use the usecols parameter to do so.

In [13]:
df = pd.read_csv('Mall_Customers.csv', usecols = ['CustomerID','Age','Spending Score (1-100)'], index_col = 'CustomerID')

In [14]:
df

            Age  Spending Score (1-100)
CustomerID
1            19                      39
2            21                      81
3            20                       6
4            23                      77
5            31                      40
...         ...                     ...
196          35                      79
197          45                      28
198          32                      74
199          32                      18
200          30                      83

[200 rows x 2 columns]